// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package viewCommon

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Animation() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Animation_9fc6`,
		Function: `function __templ_Animation_9fc6(){const observer = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    console.log(entry);
    if (entry.isIntersecting) {
      entry.target.classList.add('show');
    } else {
      entry.target.classList.remove('show');
    }
  });
});

const hiddenElementsLeft = document.querySelectorAll('.hiddenLeft');
const hiddenElementsRight = document.querySelectorAll('.hiddenRight');

hiddenElementsLeft.forEach((el) => observer.observe(el));
hiddenElementsRight.forEach((el) => observer.observe(el));

gsap.registerPlugin(ScrollTrigger);

// Navbar Animation
gsap.from('.navbar', {
  duration: 1,
  opacity: 0,
  y: -50,
  ease: Power3.easeInOut
});

// Header Animations
gsap.from('.logo-animate', 1, {
  opacity: 0,
  x: -20,
  ease: Expo.easeInOut
}, 0.08);

gsap.from('.navbar-animate', 1, {
  duration: 0.6,
  opacity: 0,
  x: 25,
  stagger: 0.15,
  ease: Power3.easeInOut
}, 0.06);

// Index Page Animations
// Hero Animations
gsap.from('.hero-animate-p', {
  duration: 0.6,
  opacity: 0,
  y: -25,
  stagger: 0.15
});

gsap.from('.hero-title-animate', 1, {
  duration: 0.25,
  opacity: 0,
  y: 30,
  x: 10,
  ease: Power3.easeInOut
}, 0.08);

gsap.from('.hero-title-animate-2', 1, {
  duration: 0.25,
  opacity: 0,
  delay: 0.2,
  y: 30,
  x: 10,
  ease: Power3.easeInOut
}, 0.08);

gsap.from('.delay-span-animate', 1, {
  duration: 0.3,
  opacity: 0,
  delay: 0.4,
  y: 25,
  x: 10,
  ease: Expo.easeInOut
}, 0.06);

// Services Animation
gsap.from('.img-animate-top-right', 1, {
  scrollTrigger: '.img-animate-top-right',
  duration: 0.8,
  blur: 50,
  opacity: 0,
  x: 10,
  y: -20
}, 0.06);

gsap.from('.img-animate-bottom-right', 1, {
  scrollTrigger: '.img-animate-bottom-right',
  duration: 0.8,
  blur: 50,
  opacity: 0,
  x: 10,
  y: 20
}, 0.06);

gsap.from('.img-animate-bottom-left', 1, {
  scrollTrigger: '.img-animate-bottom-left',
  duration: 0.8,
  blur: 50,
  opacity: 0,
  x: -10,
  y: 20
}, 0.06);

// Personal Trainers Animation
gsap.from('.animate-team', {
  scrollTrigger: '.animate-team',
  duration: 1,
  opacity: 0,
  y: -100,
  stagger: 0.3,
  delay: 0.2
});

gsap.from('.animate-email', {
  scrollTrigger: '.animate-email',
  duration: 0.4,
  opacity: 0,
  y: -120,
  stagger: 0.2,
  delay: 0.4
});

// Memberships Animations
gsap.from('.memb-animate-left', 1, {
  scrollTrigger: '.memb-animate-left',
  duration: 1,
  opacity: 0,
  x: -500,
  stagger: 0.15,
  blur: 20
}, 0.06);

gsap.from('.memb-animate-right', 1, {
  scrollTrigger: '.memb-animate-right',
  duration: 1,
  opacity: 0,
  x: 500,
  stagger: 0.15,
  blur: 20
}, 0.06);

gsap.from('.memb-animate-bottom', 1, {
  scrollTrigger: '.memb-animate-bottom',
  duration: 1,
  opacity: 0,
  y: 500,
  stagger: 0.15,
  blur: 20,
  delay: 0.05
}, 0.06);
}`,
		Call:       templ.SafeScript(`__templ_Animation_9fc6`),
		CallInline: templ.SafeScriptInline(`__templ_Animation_9fc6`),
	}
}

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar\"><a href=\"index.html\"><img src=\"./logos/sparta-logo-red.png\" alt=\"envizion-logo\" class=\"navbar-logo logo-animate\"></a> <a href=\"index.html\"><h1 class=\"logo-animate\">En<span>Vizion</span> Gym</h1></a><div class=\"navbar-toggle\" id=\"mobile-menu\"><span class=\"bar\"></span> <span class=\"bar\"></span> <span class=\"bar\"></span></div><div class=\"navbar-menu navbar-animate\"><a href=\"index.html\" class=\"navbar-link\">Home</a> <a href=\"news.html\" class=\"navbar-link\">News</a> <a href=\"services.html\" class=\"navbar-link\">Services</a> <a href=\"group-programs.html\" class=\"navbar-link \">Group Programs</a> <a href=\"membership.html\" class=\"navbar-link \">Memberships</a> <a href=\"about-us.html\" class=\"navbar-link\">About Us</a> <a href=\"contact.html\" class=\"navbar-link\">Contact</a> <button class=\"login-btn\">Login<div class=\"tooltip\"><p class=\"margin\">Don't Have an Account?</p><p>You can Sign Up</p></div></button></div></nav><script>\n\t\tNavbar();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
