// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package viewCommon

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar\"><a href=\"index.html\"><h1 class=\"logo-animate\">En<span>Vizion</span> Gym</h1></a><div class=\"navbar-toggle\" id=\"mobile-menu\"><span class=\"bar\"></span> <span class=\"bar\"></span> <span class=\"bar\"></span></div><div class=\"navbar-menu navbar-animate\"><a href=\"index.html\" class=\"navbar-link\">Home</a> <a href=\"news.html\" class=\"navbar-link\">News</a> <a href=\"services.html\" class=\"navbar-link\">Services</a> <a href=\"group-programs.html\" class=\"navbar-link \">Group Programs</a> <a href=\"membership.html\" class=\"navbar-link \">Memberships</a> <a href=\"about-us.html\" class=\"navbar-link\">About Us</a> <a href=\"contact.html\" class=\"navbar-link\">Contact</a> <button class=\"login-btn\">Login<div class=\"tooltip\"><p class=\"margin\">Don't Have an Account?</p><p>You can Sign Up</p></div></button></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
